### ISSUE TITLE
Hard times with installing WikidPad on Mac

### ISSUE THREAD

**Issue by mrtvocich** [WikidPad/WikidPad#65]
Hi WikidPad community. I was using this software around 10 years ago and since I switched to Mac around also many years ago, I wasn't really able to use WikidPad on Mac OS. Is anyone there who would be so kind to help me with Python and PythonWx? I've tried several times during last few years to make it work, but I've everytime ended up fighting with Terminal and never with WikidPad running. If anyone would have time on Jabber or by Zoom call to help with setting up WikidPad on Mac, I would be really grateful. Cheers, mrtvocich

**Comment by paulywill** [comment]
>  If anyone would have time on Jabber or by Zoom call to help with setting up WikidPad on Mac, I would be really grateful. Cheers, mrtvocich

I too would be interested in this, or if someone would be kind enough to record said call as a walk-through for others.

**Comment by BjornFJohansson** [comment]
What are the problems that you face when trying? Is running from source an alternative? I run wikidpad from the source code using the anaconda python distro on linux and windows which works very well, but there seems to have been problems with refreshing on Mac. This seemed to me at the time to be a problem in wxpython. That is several years ago now, so perhaps these problems have been fixed?

**Comment by vashnt707** [comment]
I tried run from source 6 month back and the issue still existed in Mac. Works in Windows and Linux though.

**Comment by mrtvocich** [comment]
System Info:
Mac OS X 10.13.6
`python --version
Python 2.7.16 `

After downloading and unzipping the code, I opened Terminal, moved to the Wikidpad downloaded folder and run

`python setup.py install`

The log is here: https://pastebin.com/pvaWcxqG

Because I am not a developer, I don't know, how to run the program afterwards. In the directory was created a new directory build/lib/ and there is WikidPadStarter.py. I've tried to type in Terminal `python /Users/mrtvocich/Downloads/wikid/build/lib/WikidPad/WikidPadStarter.py 
Traceback (most recent call last):
  File "/Users/mrtvocich/Downloads/wikid/build/lib/WikidPad/WikidPadStarter.py", line 11, in <module>
    import sys, os, traceback, os.path, glob, shutil, imp, warnings, configparser
ImportError: No module named configparser`

Any ideas? Thanks for every input.

**Comment by vashnt707** [comment]
Pip install configparser

**Comment by mrtvocich** [comment]
Okay, I don't know what has changed, but now when I run `python WikidPadStarter.py` I get

mrtvocich@Marek-MacBook:~/Downloads/wikid_1/build/lib/WikidPad$ python WikidPadStarter.py 
Traceback (most recent call last):
  File "WikidPadStarter.py", line 14, in <module>
    origin = __spec__.origin
NameError: name '__spec__' is not defined
mrtvocich@Marek-MacBook:~/Downloads/wikid_1/build/lib/WikidPad$ 

I installed the configparser successfully.

**Comment by vashnt707** [comment]
Possibly invalid path to package root causing the modules not being recognized. I don't want to discourage you but WikidPad on Mac is not going to work in its current state.

**Comment by mrtvocich** [comment]
Okay:( Thanks anyways, at least I know that I've tried it. I'll might try using the Wine emulation.

**Comment by pvanhese** [comment]
This works for me on macOS Catalina 10.15.7:

1. Install [Anaconda Individual Edition](https://www.anaconda.com/products/individual), pick the 64-Bit Command Line Installer (so you'll have `conda` available in the terminal).

2. Clone the WikidPad repository with [git](https://git-scm.com/download/mac):
```
$ git clone https://github.com/WikidPad/WikidPad.git
```

3. [Create an environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) named "wikidpad", include the package `wxpython`:
```
$ conda create -n wikidpad wxpython
```

4. Activate the environment, run WikidPad:
```
$ conda activate wikidpad
$ cd WikidPad
$ pythonw WikidPad.py   # note: use `pythonw`, not `python`
```

I get some debug messages ("No accel key found"), but other than that it looks ok.

Hope this helps.

**Comment by mrtvocich** [comment]
Hi pvanhese! Thanks a lot for the guide. I have followed all the steps, but unfortunately it seems like that on OS X 10.13.6 there are some graphic issues. The program run, but I can't type a don't see the text cursor. Also resizing of a window makes the whole program black. I have even tried creating a new user, re-download everything in a fresh environment, but unfortunately it didn't help. I really appreciate your time though, thank you. I hope it will help other users. I guess I will just have to use Wine.

[http://mrtvocich.troska.cz/uploader/files/a.png]()
[http://mrtvocich.troska.cz/uploader/files/b.png]()

**Comment by vashnt707** [comment]
I just tested @pvanhese steps on my Mac Catalina 10.15.7 and faced same issue as @mrtvocich

**Comment by mrtvocich** [comment]
I ended up with running wikidPad 2.3rc01 through WineBottler 4.0.1.1 (rc02 was after start giving constantly a notice that the app language can't be set to the OS default. In winetricks I didn't add anything. Emulated OS: Win 10 (only, not 64). I hope this will help some desperate Mac OS X users.

**Comment by mrtvocich** [comment]
_Small update for Mac users:_ 

I have discovered that WineSkin project is still being developed by a few guys and works very well. Running apps through it allows to remap the Cmd and Alt keys so you can use Cmd as a Ctrl and so on. WikidPad also allow to make your own shortcuts - search the default Wiki the loads after fresh install. 

WineSkin link: [https://github.com/Gcenx/WineskinServer/tree/master/Winery](https://github.com/Gcenx/WineskinServer/tree/master/Winery)

**Comment by BjornFJohansson** [comment]
@pvanhese what version of python do you end up running? and wxpython? Could you perhaps post the results from `conda list` ?

**Comment by pvanhese** [comment]
@BjornFJohansson @mrtvocich 

```
$ python -V
Python 3.7.9
```

```
$ conda list
# Name                    Version                   Build  Channel
backports                 1.0                pyhd3eb1b0_2
backports.lzma            0.0.14           py37hd621484_0
ca-certificates           2020.10.14                    0
certifi                   2020.6.20          pyhd3eb1b0_3
expat                     2.2.10               hb1e8313_2
gettext                   0.19.8.1             hb0f4f8b_2
jpeg                      9b                   he5867d9_2
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
libiconv                  1.16                 h1de35cc_0
libpng                    1.6.37               ha441bb4_0
ncurses                   6.2                  h0a44026_1
openssl                   1.1.1h               haf1e3a3_0
pip                       20.2.4           py37hecd8cb5_0
python                    3.7.9                h26836e1_0
python.app                2                       py37_10
readline                  8.0                  h1de35cc_0
setuptools                50.3.1           py37hecd8cb5_1
six                       1.15.0           py37hecd8cb5_0
sqlite                    3.33.0               hffcf06c_0
tk                        8.6.10               hb0a8c7a_0
wheel                     0.35.1             pyhd3eb1b0_0
wxpython                  4.0.4            py37hebc47a7_0
xz                        5.2.5                h1de35cc_0
zlib                      1.2.11               h1de35cc_3
```

**Comment by mrtvocich** [comment]
Nice. Is it somehow possible to try run wP with this config?

**Comment by mrtvocich** [comment]
Btw thanks guys for so many replies :D I am glad for that!

**Comment by moxita** [comment]
After upgrading my M1 Mac to Monterey, WikidPad broke!  I have tried so many things... tried to install Python 2, tried to use Rosetta, tried to use 2to3 to convert the code to work with Python 3. Finally I also tried installing using Wine and the EXE file installs, but only a blank WikidPadHelp window opens with no options to open new Wikis.  Has anyone gotten WikidPad to work on Monterey?

**Comment by BjornFJohansson** [comment]
@moxita, have you tried running from source using anaconda or some other python distro?

**Comment by moxita** [comment]
Sort of, but I got stuck. I used the following 
```
CONDA_SUBDIR=osx-64 conda create -n py27 python=2.7  # include other packages here

# ensure that future package installs in this env stick to 'osx-64'
conda activate py27
conda config --env --set subdir osx-64
```
in a Rosetta terminal to get a Python2 environment, per https://stackoverflow.com/questions/67380286/anaconda-channel-for-installing-python-2-7

Then, I used `conda install wxPython`

Finally, I went into the source dir (WikidPad-2.2-src) and ran 
`python2 WikidPad.py`  but ended up with the following errors:

> **Traceback (most recent call last):
  File "WikidPad.py", line 1, in <module>
    import WikidPadStarter
  File "/Users/mydir/Documents/WikidPad-2.2-src/WikidPadStarter.py", line 111, in <module>
    from pwiki.MainApp import App, findDirs
  File "lib/pwiki/MainApp.py", line 27, in <module>
    import WindowLayout
  File "lib/pwiki/WindowLayout.py", line 10, in <module>
    from .wxHelper import LayerSizer, ProxyPanel
  File "lib/pwiki/wxHelper.py", line 726, in <module>
    class wxKeyFunctionSink(wx.EvtHandler, KeyFunctionSink):
TypeError: Error when calling the metaclass bases
    multiple bases have instance lay-out conflict**

**Comment by BjornFJohansson** [comment]
I think you would have an easier time with python 3 and one of the wxpythons that are adapted for python 3.
Python 2 has been deprecated since quite long time now.
